# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\"2\n\x04Info\x12\x0b\n\x03\x63id\x18\x01 \x02(\t\x12\r\n\x05level\x18\x02 \x02(\x05\x12\x0e\n\x06reward\x18\x03 \x02(\x02\"\x15\n\x03\x41\x63t\x12\x0e\n\x06\x61\x63tion\x18\x01 \x02(\x05\x32\x1f\n\x06\x41\x63tion\x12\x15\n\x06\x61\x63tion\x12\x05.Info\x1a\x04.Act2\x1d\n\x05Reset\x12\x14\n\x05reset\x12\x05.Info\x1a\x04.ActB\x0bZ\t.detector')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t.detector'
  _globals['_INFO']._serialized_start=13
  _globals['_INFO']._serialized_end=63
  _globals['_ACT']._serialized_start=65
  _globals['_ACT']._serialized_end=86
  _globals['_ACTION']._serialized_start=88
  _globals['_ACTION']._serialized_end=119
  _globals['_RESET']._serialized_start=121
  _globals['_RESET']._serialized_end=150
# @@protoc_insertion_point(module_scope)
